// <auto-generated />
namespace teste.burguer.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class alterar6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alterar6));
        
        string IMigrationMetadata.Id
        {
            get { return "201903260110207_alterar6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
